FROM ubuntu:16.04

ENV PATH="/cmake-3.11.4-Linux-x86_64/bin:${PATH}"

RUN apt-get -y update
RUN apt-get -y install sudo git clang-format gcc g++ make 
# since cmake is not latest in apt-get repository,so we install it separately
RUN sudo wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
RUN tar xf cmake-3.11.4-Linux-x86_64.tar.gz


# dont change PATH, just replay old cmake with new one
#FROM ubuntu:16.04

#RUN apt-get -y update
#RUN apt-get -y install sudo git clang-format gcc g++ make 
#RUN sudo wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
#RUN tar xf cmake-3.11.4-Linux-x86_64.tar.gz
#RUN sudo mv cmake-3.11.4-Linux-x86_64/bin/cmake /usr/bin/cmake
